### ISSUE TITLE
Breadcrumb links lead to 404 error when parent page does not exist

### ISSUE THREAD

**Issue by browningjp** [justinwalsh/daux.io#289]
Say you have a menu item with children, that does not have an index.md page. The menu item is merely a parent to its children, it does not link to any real page.

If you load a child of this menu item, a breadcrumb appears at the top of the page "Parent -> Child". If you click on the Parent link in the breadcrumb, it takes you to a 404 error page.

**Comment by onigoetz** [comment]
Fixed in the development branch, it's going to be merged asap. can you please try it ?

**Comment by browningjp** [comment]
Now throwing an error:
"Fatal error: Class 'Todaymade\Daux\Server\Server' not found in [path] on line 87"

Tried using the index.php file from the master branch, which worked, but had the same problem as before.
Annoyingly the server I'm having to use ignores .htaccess files - don't know if this is at all relevant?

**Comment by onigoetz** [comment]
If your server doesn't understand .htaccess, try setting "clean_urls" to false in your configuration

**Comment by browningjp** [comment]
Ah yes, I had already set that, but still getting the errors as mentioned
before :/

**Comment by onigoetz** [comment]
Maybe you get the fatal error because you're half on the latest version and half on the previous version.

If you try the latest version, try to remove the `vendor` and `libs` folders. 

you should only keep : `resources`, `daux.phar`, `global.json`, `generate`, `serve` and `index.php`

**Comment by browningjp** [comment]
I'm now getting a different error:
"Parse error: syntax error, unexpected '[', expecting ')' in
phar:///[path]/daux.phar/vendor/react/promise/src/functions.php on line 68"

**Comment by onigoetz** [comment]
What version of php are You running on ? Maybe you are on php 5.3, php 5.4 is required as a minimum now

**Comment by browningjp** [comment]
Ah, that would be it. Sadly I have no control over the PHP installation
myself :( Looks like I will have to stick to using the current master
branch with no
 categories unless they have their own page associated with them!

Thanks a lot for your support

Jonny
