### ISSUE TITLE
Multilanguage Landingpage

### ISSUE THREAD

**Issue by wiggisser** [justinwalsh/daux.io#434]
I'm a bit stuck here with multilanguages, maybe there is some config option or I'm doing it wrong.

Prerequisites: 

I have the following directory structure:

```
/docs
  _index.md
  de
    01_some_folder
      01_some_file
      02_somefile
    02_some_folder
      02_some_file
      02_some_file
  en
    01_some_folder
      01_some_file
      02_somefile
    02_some_folder
      02_some_file
      02_some_file
```

and my config looks like this

```
{
    "title": "My Knowledgebase",

    "languages": {
        "en": "English",
        "de": "Deutsch"
    },

    "html": {
      "search": true,
    }
}
```

If I generate the static files and browse to http://docs.mydomain.com I see the landing page like this

![image](https://cloud.githubusercontent.com/assets/3647678/22146866/8551f7a4-df06-11e6-8df8-64147bf9a620.png)

Is there any way to hide the navigation tree here. I would like to insert the links to the german and english version as http://docs.mydomain.com/de and http://docs.mydomain.com/en respectively in the landing page. 

And that's the next problem, with my current directory structure, there is no landing page for each language generated so linking to http://docs.mydomain.com/de results in an error. I tried to add a simple _index.md to both of the languages, but then I see the following when I go to http://docs.mydomain.com/de

![image](https://cloud.githubusercontent.com/assets/3647678/22147141/910f6bca-df07-11e6-8efe-e01f1ba7c0ba.png)

Here it would be nice just to see the content of my landing page and a naviagtion tree for the respective language

**Comment by wiggisser** [comment]
OK, I found a workaround for the second problem, just don't name the landing page for each language as `index.md` but for instance `00_start.md` than I can link to `de/start.md` and `en/start.md` in the general landing page. Furthermore I configured my webserver to also accept `start.html` as default so I can now link directly to `http://docs.mydomain.com/de` and `http://docs.mydomain.com/en`

**Comment by onigoetz** [comment]
Hello,
do you use the latest version from packagist with composer ?

It seems this should have been fixed a few weeks ago.

**Comment by wiggisser** [comment]
Thanks for your answer. Actually, at the time I filed this issue I was using the version which I got via the "Download" link from https://daux.io. I'm not sure how old this version was (as I later switched to a version cloned from github). I also found out, that if I use the  {"auto_landing": "false"} setting, it works fine for me, just forgot to put a comment here. Sorry for that.

**Comment by wiggisser** [comment]
Maybe I'm just using it wrong, but as I'm not a php guy I never even heard of composer. this is what I did (I'm on linux mint): 

apt-get install composer
git clone https://github.com/justionwalsh/daux.io
composer global require justinwalsh/daux.io

but I still get "daux: command is not available"

So I just tried to use './bin/daux --generate' and this seemed to work
